db_path        = "~/.local/share/atuin/history.db"
dialect        = "us"
enter_accept   = true
history_filter = ["^secret-cmd", "^innocuous-cmd .*--secret=.+"]
inline_height  = 21
search_mode    = "fuzzy"
style          = "compact"
sync_frequency = "1h"
word_jump_mode = "emacs"
