start-at-login                                                  = true
enable-normalization-flatten-containers                         = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding                                               = 38
default-root-container-layout                                   = 'accordion'
default-root-container-orientation                              = 'vertical'
automatically-unhide-macos-hidden-apps                          = true

[key-mapping]
  preset = 'qwerty'

[gaps]
  inner.horizontal = 8
  inner.vertical   = 8
  outer.left       = 8
  outer.bottom     = 8
  outer.top        = 8
  outer.right      = 8

[mode.main.binding]
  alt-w     = 'mode window'
  alt-slash = 'mode service'
  alt-g     = 'mode pass'

  alt-comma  = 'layout accordion horizontal vertical'
  alt-period = 'layout tiles horizontal vertical'

  alt-b = 'exec-and-forget open -a /Applications/Google\ Chrome.app'
  alt-c = 'exec-and-forget open -a /Applications/Cursor.app'
  alt-t = 'exec-and-forget open -a /Applications/Ghostty.app'
  alt-z = 'exec-and-forget open -a /Applications/Zed.app'

  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  alt-4 = 'workspace 4'
  alt-5 = 'workspace 5'
  alt-6 = 'workspace 6'
  alt-7 = 'workspace 7'
  alt-8 = 'workspace 8'
  alt-9 = 'workspace 9'
  alt-0 = 'workspace 10'

  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'
  alt-shift-4 = 'move-node-to-workspace 4'
  alt-shift-5 = 'move-node-to-workspace 5'
  alt-shift-6 = 'move-node-to-workspace 6'
  alt-shift-7 = 'move-node-to-workspace 7'
  alt-shift-8 = 'move-node-to-workspace 8'
  alt-shift-9 = 'move-node-to-workspace 9'
  alt-shift-0 = 'move-node-to-workspace 10'

  alt-h = 'focus left --boundaries all-monitors-outer-frame'
  alt-j = 'focus down --boundaries all-monitors-outer-frame'
  alt-k = 'focus up --boundaries all-monitors-outer-frame'
  alt-l = 'focus right --boundaries all-monitors-outer-frame'

  alt-tab = 'workspace-back-and-forth'

  cmd-m = []
  cmd-h = []

[mode.pass.binding]
  alt-g = 'mode main'

[mode.window.binding]
  esc = 'mode main'

  h       = 'move left'
  j       = 'move down'
  k       = 'move up'
  l       = 'move right'
  shift-h = "move-node-to-monitor left"
  shift-j = "move-node-to-monitor down"
  shift-k = "move-node-to-monitor up"
  shift-l = "move-node-to-monitor right"
  alt-h   = ['join-with left', 'mode main']
  alt-j   = ['join-with down', 'mode main']
  alt-k   = ['join-with up', 'mode main']
  alt-l   = ['join-with right', 'mode main']

  minus = 'resize smart -50'
  equal = 'resize smart +50'

  1 = ['move-node-to-workspace 1', 'mode main']
  2 = ['move-node-to-workspace 2', 'mode main']
  3 = ['move-node-to-workspace 3', 'mode main']
  4 = ['move-node-to-workspace 4', 'mode main']
  5 = ['move-node-to-workspace 5', 'mode main']
  6 = ['move-node-to-workspace 6', 'mode main']
  7 = ['move-node-to-workspace 7', 'mode main']
  8 = ['move-node-to-workspace 8', 'mode main']
  9 = ['move-node-to-workspace 9', 'mode main']
  0 = ['move-node-to-workspace 11', 'mode main']

  r         = ['flatten-workspace-tree', 'mode main']
  backspace = ['close-all-windows-but-current', 'mode main']

  f       = ['layout floating tiling', 'mode main']
  shift-f = ['fullscreen', 'mode main']

[mode.service.binding]
  esc = 'mode main'

  cmd-r = ['reload-config', 'mode main']

[[on-window-detected]]
  if.app-id = 'com.xingin.discover'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.jihuanshe.app'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.xfge.LifeEasy'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'app.podcast.cosmos'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.miHoYo.hkrpg'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.miHoYo.Nap'
  run       = 'layout floating'

[[on-window-detected]]
  if.window-title-regex-substring = 'MDPro3'
  run                             = 'layout floating'

[[on-window-detected]]
  if.window-title-regex-substring = 'steam'
  run                             = 'layout floating'

[[on-window-detected]]
  if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'org.pqrs.Karabiner-EventViewer'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.1password.1password'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.timpler.screenstudio'
  run       = 'layout floating'

[[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  run       = 'move-node-to-workspace 1'

[[on-window-detected]]
  if.app-id = 'com.tencent.xinWeChat'
  run       = 'move-node-to-workspace 2'

[[on-window-detected]]
  if.app-id = 'com.todesktop.230313mzl4w4u92'
  run       = 'move-node-to-workspace 9'

[[on-window-detected]]
  if.app-id = 'com.exafunction.windsurf'
  run       = 'move-node-to-workspace 9'
