# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Dates
  - trigger: "#sd"
    replace: "{{shortdate}}"
    vars:
      - name: shortdate
        type: date
        params:
          format: "%y%m%d"
  - trigger: "#fd"
    replace: "{{fulldate}}"
    vars:
      - name: fulldate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "#st"
    replace: "{{shorttime}}"
    vars:
      - name: shorttime
        type: date
        params:
          format: "%H:%M"

  # Shell commands
  - trigger: "#ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "ifconfig | grep 'inet ' | grep -Fv 127.0.0.1 | awk '{print $2}'"
          shell: bash

  # Roam
  - trigger: "【【"
    replace: "[[$|$]]"
  - trigger: "（（"
    replace: "(($|$))"
  - trigger: "；；"
    replace: ;;

  # Software abbreviations
  - trigger: "#rm"
    replace: "Roam Research"

  # Mac symbols

  # My
  - trigger: "#my"
    form: |
      🙋‍♂️ Hi，很高兴认识你～ 我的博客是 👉 {{blog}} 你也在 Telegram 上找到我 👉 {{telegram}}
    form_fields:
      text:
        multiline: true

  - trigger: "#@m"
    form: |
      {{Mail}}
    form_fields:
      text:
        multiline: true
