jobs:
  # - name: kill ScreenTimeAgent
  #   command: |
  #     launchctl kickstart -k gui/$UID/com.apple.ScreenTimeAgent
  #   shell: /bin/zsh
  #   schedule: "0 * * * *"
  #   captureStderr: true
  #   onFailure:
  #     report:
  #       shell:
  #         shell: /bin/zsh
  #         command: echo "Error code $YACRON_RETCODE"
  # - name: Backup Homebrew
  #   command: |
  #     brew bundle dump --file="$HOME"/dotfiles/assets/others/packages/Brewfile --force
  #   shell: /bin/zsh
  #   schedule: "0 0 * * *"
  #   captureStderr: true
  #   onFailure:
  #     report:
  #       shell:
  #         shell: /bin/zsh
  #         command: echo "Error code $YACRON_RETCODE"
  - name: Backup Others
    command: |
      brew leaves >"$HOME"/dotfiles/assets/others/packages/Brewfile.txt
      cargo install --list | grep -v '^[[:blank:]]' | awk '{print $1}' >"$HOME"/dotfiles/assets/others/packages/cargo.txt
      pipx list --json | jq ".venvs | .[] | .metadata.main_package.package" -r >"$HOME"/dotfiles/assets/others/packages/pipx.txt
      npm list --global --depth=0 --json | jq ".dependencies | keys[]" -r >"$HOME"/dotfiles/assets/others/packages/npm.txt
      code --list-extensions >"$HOME"/dotfiles/assets/others/packages/vscode_extensions.txt
      ls /Applications | rg '\.app' | sed 's/\.app//g' >"$HOME"/dotfiles/assets/others/packages/macos_applications.txt
      ls /Applications/Setapp | rg '\.app' | sed 's/\.app//g' >"$HOME"/dotfiles/assets/others/packages/macos_setapp.txt
      cp "$HOME"/.zsh_history /Volumes/Bookshelf/Database/Backup/CLI/zsh_history_$(date +\%Y_\%m_\%d).bak
    shell: /bin/zsh
    schedule: "0 1,13,20 * * *"
    captureStderr: true
    onFailure:
      report:
        shell:
          shell: /bin/zsh
          command: echo "Error code $YACRON_RETCODE"
