jobs:
  - name: kill input method
    command: |
      kill -9 'pgrep SCIM'
      kill -9 'pgrep Spotlight'
    shell: /bin/zsh
    schedule: "0 */2 * * *"
    captureStderr: true
    onFailure:
      report:
        shell:
          shell: /bin/zsh
          command: echo "Error code $YACRON_RETCODE"
