[tools]
"cargo:koji" = "latest"
"go:github.com/appleboy/CodeGPT/cmd/codegpt" = "latest"
"go:github.com/pouriyajamshidi/tcping/v2" = "latest"
"pipx:chainforge" = "latest"
"pipx:deepl-cli" = "latest"
"pipx:llm" = "latest"
"pipx:mackup" = "latest"
"pipx:ttok" = "latest"
"pipx:vastai" = "latest"
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "3.13.1"
ruby = "latest"
rust = "latest"
uv = "latest"
zig = "latest"

[settings]
experimental = true
plugin_autoupdate_last_check_duration = '1 week'
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
trusted_config_paths = ['~/Developer']
