palette = "catppuccin_mocha"
format = """
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$package\
$cmd_duration\
$battery\
$character"""
add_newline = false
command_timeout = 1_000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[sudo]
disabled = false
format = '[$symbol]($style)'
style = "bold red"
symbol = 'SU '

[username]
format = '[$user@]($style)'
style_root = "bold red"
style_user = "bold yellow"

[hostname]
format = '[$hostname]($style) '
style = "bold yellow"

[directory]
truncation_length = 4 
truncate_to_repo = true
truncation_symbol = '…/'
read_only_style = "bold red"
read_only = ' [RO]'

[git_branch]
format = "[$branch]($style) "
ignore_branches = ["main", "master", "develop", "dev"]

[package]
format = '[$version]($style) '

[cmd_duration]
format = '[$duration]($style) '
min_time = 10_000
min_time_to_notify = 100_000
show_milliseconds = false

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[<](bold green)'
vimcmd_replace_one_symbol = '[<](bold purple)'
vimcmd_replace_symbol = '[<](bold bold purple)'
vimcmd_visual_symbol = '[<](bold yellow)'

[[battery.display]]
threshold = 20

[[battery.display]]
threshold = 40
