palette = "catppuccin_mocha"
format = "$sudo$directory$package$all$custom$character"
add_newline = false
command_timeout = 1_000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[conda]
ignore_base = false

[character]
success_symbol = '[>](bold peach)'
error_symbol = '[>](bold peach)'
vicmd_symbol = '[>](bold subtext1)'

[custom.x86_64]
command = 'echo  '
when = 'test "$(uname -m)" = "x86_64"'

[[battery.display]]
threshold = 20
style = 'red'

[[battery.display]]
threshold = 40
style = 'yellow'

[cmd_duration]
format = 'took [$duration]($style) '
min_time = 10_000
min_time_to_notify = 240_000
show_milliseconds = false

[directory]
read_only = '  '
read_only_style = 'red'
truncation_length = 4
truncate_to_repo = true
truncation_symbol = '…/'
style = "bold lavender"

[git_branch]
symbol = ' '
truncation_length = 16
truncation_symbol = '…'
ignore_branches = ['master', 'main']
style = "bold mauve"

[docker_context]
symbol = ' '

[golang]
symbol = ' '

[java]
symbol = ' '

[python]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[swift]
symbol = ' '

[package]
symbol = ' '

[sudo]
format = '[$symbol]($style)'
disabled = false
style = 'bold green'
symbol = ' '
