[[cable_channel]]
name = "hidden-files"
source_command = "fd --type file --hidden --follow --exclude .git --exclude .venv --exclude .DS_Store"
preview_command = ":files:"

[[cable_channel]]
name = "py-files"
source_command = "fd --type file --extension py --follow --exclude .git --exclude .venv --exclude .DS_Store"
preview_command = ":files:"

[[cable_channel]]
name = "brew-packages"
source_command = "brew list --installed-on-request"
preview_command = "brew info {0}"

[[cable_channel]]
name = "hosts"
source_command = "grep '^Host ' ~/.ssh/config | grep -v '[*]' | awk '{print $2}'"
preview_command = "grep -A 5 'Host {0}' ~/.ssh/config"

[[cable_channel]]
name = "known-hosts"
source_command = "cat ~/.ssh/known_hosts | awk '{print $1}' | sort -u"
preview_command = "dig {0}"

[[cable_channel]]
name = "sessions"
source_command = "zellij list-sessions --no-formatting --short"

[[cable_channel]]
name = "gists"
source_command = "gh api --paginate /gists | jq -r '.[] .files[] | .raw_url'"
preview_command = "curl --silent {0}"

[[cable_channel]]
name = "py-gists"
source_command = "gh api --paginate /gists | jq -r '.[] .files[] | select(.filename | endswith(\".py\")) | .raw_url'"
preview_command = "curl --silent {0}"

[[cable_channel]]
name = "tv-channels"
source_command = "tv list-channels | grep -v 'channels:' | sed '/^[[:space:]]*$/d' | sed 's/^[[:space:]]*//'"

[[cable_channel]]
name = "notes"
source_command = "fd . '/Users/alex/Databases/Roam' --type file --extension md"
preview_command = ":files:"
