[[cable_channel]]
name = "hidden-files"
source_command = "fd --no-ignore-vcs --type file --hidden --follow"
preview_command = ":files:"

[[cable_channel]]
name = "shell-scripts"
source_command = "fd --no-ignore-vcs --type file --extension sh"
preview_command = ":files:"

[[cable_channel]]
name = "python-scripts"
source_command = "fd --no-ignore-vcs --type file --extension py"
preview_command = ":files:"

[[cable_channel]]
name = "brew-packages"
source_command = "brew list --installed-on-request"
preview_command = "brew info {0}"

[[cable_channel]]
name = "brew-bins"
source_command = "ls /opt/homebrew/bin 2>/dev/null | sort -u"
preview_command = "man {0}"

[[cable_channel]]
name = "hosts"
source_command = "grep '^Host ' ~/.ssh/config | grep -v '[*]' | awk '{print $2}'"
preview_command = "grep -A 5 'Host {0}' ~/.ssh/config"

[[cable_channel]]
name = "known-hosts"
source_command = "cat ~/.ssh/known_hosts | awk '{print $1}' | sort -u"
preview_command = "dig {0}"

[[cable_channel]]
name = "zellij-sessions"
source_command = "zellij list-sessions --no-formatting --short"

[[cable_channel]]
name = "gists"
source_command = "gh api --paginate /gists | jq -r '.[] .files[] | .raw_url'"
preview_command = "curl --silent {0}"

[[cable_channel]]
name = "py-gists"
source_command = "gh api --paginate /gists | jq -r '.[] .files[] | select(.filename | endswith(\".py\")) | .raw_url'"
preview_command = "curl --silent {0}"

[[cable_channel]]
name = "channels"
source_command = "tv list-channels | grep -v 'channels:' | sed '/^[[:space:]]*$/d' | sed 's/^[[:space:]]*//'"

[[cable_channel]]
name = "roam-notes"
source_command = "fd . '/Users/alex/Databases/Roam' --type file --extension md"
preview_command = ":files:"

[[cable_channel]]
name = "custom-shell-scripts"
source_command = "fd . /Users/alex/Developer/local/prototypes/utils --type file --extension sh"
preview_command = ":files:"

[[cable_channel]]
name = "custom-python-scripts"
source_command = "fd . /Users/alex/Developer/local/prototypes/utils --type file --extension py"
preview_command = ":files:"
