# ~/.config/starship.toml

format = '''$all$custom'''

command_timeout = 1000

[character]
    success_symbol = "[>](bold green)"
    vicmd_symbol   = "[>](bold yellow)"
    error_symbol   = "[>](bold red)"

[custom.x86_64]
    command = "echo  "
    when    = 'test "$(uname -m)" = "x86_64"'

[aws]
    symbol   = " "
    disabled = true

[battery]
    full_symbol        = ""
    charging_symbol    = ""
    discharging_symbol = ""

[[battery.display]]
    threshold = 15
    style     = "red"

[[battery.display]]
    threshold = 30
    style     = "yellow"

[conda]
    symbol = " "

[cmd_duration]
    # show_milliseconds = true
    min_time = 10_000 # Show command duration over 10,000 milliseconds (=10 sec)

[directory]
    read_only         = "  "
    read_only_style   = "red"
    truncation_length = 3
    truncate_to_repo  = false
    truncation_symbol = ".../"

[docker_context]
    symbol = " "

[git_branch]
    symbol = " "

[git_status]
    ahead    = "⇡${count}"
    diverged = "⇕⇡${ahead_count}⇣${behind_count}"
    behind   = "⇣${count}"

[golang]
    symbol = " "

[hg_branch]
    symbol = " "

    # [hg_branch]
    # format = "on [🌱 $branch](bold purple)"
    # truncation_length = 4
    # truncation_symbol = ""

[java]
    symbol = " "

    # [memory_usage]
    # symbol = " "
    # disabled = false
    # threshold = 90
    # style = "bold dimmed green"

[package]
    symbol = " "

[python]
    symbol = " "

[ruby]
    symbol = " "

[rust]
    symbol = " "

[swift]
    symbol = "ﯣ "
