name: ci
on: [push, pull_request]
jobs:
  ci:
    name: run ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: set up
        run: |
          git clone --depth 1 https://github.com/ipruning/dotfiles.git $HOME/dotfiles
          cd $HOME/dotfiles
          ./scripts/bootstrap_ci.sh
      - name: run test
        run: |
          ./tests/test_ci.sh
