name: build
on: [push, pull_request]
jobs:
  ci:
    name: run
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          git clone --depth 1 https://github.com/Spehhhhh/dotfiles.git "$HOME"/dotfiles
          cd "$HOME"/dotfiles
          ./bootstrap.sh --force
