name: build
on: [push, pull_request]
jobs:
  ci:
    name: run
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - name: bootstrap
        run: sh ./scripts/bootstrap_mac.sh
      - name: test
        run: sh ./test/test_mac.sh
